apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy 
    orgId: 1
    url: http://${LOKI_FQDN}:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://${PROMETHEUS_FQDN}:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false

  - name: Alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://${ALERTMANAGER_FQDN}:9093
    basicAuth: false
    isDefault: false
    version: 1
    editable: false