FROM grafana/grafana:latest

# Set environment variables for initial setup
ENV GF_SECURITY_ADMIN_USER=admin
ENV GF_SECURITY_ADMIN_PASSWORD=admin
ENV GF_USERS_ALLOW_SIGN_UP=false

EXPOSE 3000

CMD ["grafana-server"]