name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (or whichever branch you want)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 1: Log in to Azure using the service principal
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use the AZURE_CREDENTIALS secret

    # Step 2: Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify that it's installed

    # Step 3: Log in to Azure Container Registry (ACR)
    - name: Log in to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # Step 4: Build Docker images from docker-compose.yml (only for api-server)
    - name: Build Docker image for api-server
      run: |
        docker-compose -f docker-compose.yml build api-server  # Build only the api-server image

    # Step 5: Pull Docker images for services from Docker Hub for other services (if not in ACR)
    - name: Pull Docker images for services from Docker Hub
      run: |
        docker pull grafana/grafana:latest
        docker pull grafana/loki:2.9.2
        docker pull prom/prometheus:latest
        docker pull prom/alertmanager:v0.27.0
        docker pull postgres:14

    # Step 6: Tag Docker images for ACR
    - name: Tag Docker images for ACR
      run: |
        # Tag API server image (built locally)
        docker tag api-server:latest ${{ secrets.ACR_LOGIN_SERVER }}/api-server:latest
        
        # Tag Grafana image
        docker tag grafana/grafana:latest ${{ secrets.ACR_LOGIN_SERVER }}/grafana:latest
        
        # Tag Loki image
        docker tag grafana/loki:2.9.2 ${{ secrets.ACR_LOGIN_SERVER }}/loki:2.9.2
        
        # Tag Prometheus image
        docker tag prom/prometheus:latest ${{ secrets.ACR_LOGIN_SERVER }}/prometheus:latest
        
        # Tag Alertmanager image
        docker tag prom/alertmanager:v0.27.0 ${{ secrets.ACR_LOGIN_SERVER }}/alertmanager:v0.27.0
        
        # Tag Postgres image
        docker tag postgres:14 ${{ secrets.ACR_LOGIN_SERVER }}/postgres:14

    # Step 7: Push Docker images to ACR
    - name: Push Docker images to ACR
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/api-server:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/grafana:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/loki:2.9.2
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/prometheus:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/alertmanager:v0.27.0
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/postgres:14

    # Step 8: Deploy postgres container to Azure Container Instances (ACI)
    - name: Deploy postgres container to Azure Container Instances (ACI)
      run: |
        az container create \
          --resource-group anatole-RG \
          --name postgres \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/postgres:14 \
          --cpu 1 --memory 2 \
          --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --ports 5432 \
          --environment-variables POSTGRES_DB=${{ secrets.POSTGRES_DB }} POSTGRES_USER=${{ secrets.POSTGRES_USER }} POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

    # Step 9: Retrieve Postgres FQDN (needed for api-server)
    - name: Retrieve Postgres FQDN
      id: fqdn_postgres
      run: |
        echo "POSTGRES_FQDN=$(az container show --resource-group anatole-RG --name postgres --query 'ipAddress.fqdn' -o tsv)" >> $GITHUB_ENV

    # Step 10: Deploy api-server container to Azure Container Instances (ACI)
    - name: Deploy api-server container to Azure Container Instances (ACI)
      run: |
        az container create \
          --resource-group anatole-RG \
          --name api-server \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/api-server:latest \
          --cpu 1 --memory 2 \
          --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --environment-variables POSTGRES_HOST=${{ env.POSTGRES_FQDN }} POSTGRES_DB=${{ secrets.POSTGRES_DB }} POSTGRES_USER=${{ secrets.POSTGRES_USER }} POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          --ports 8080

    # Step 11: Retrieve api-server FQDN (needed for Prometheus, Loki, Alertmanager)
    - name: Retrieve api-server FQDN
      id: fqdn_api_server
      run: |
        echo "API_SERVER_FQDN=$(az container show --resource-group anatole-RG --name api-server --query 'ipAddress.fqdn' -o tsv)" >> $GITHUB_ENV

    # Step 12: Deploy Loki container to Azure Container Instances (ACI)
    - name: Deploy loki container to Azure Container Instances (ACI)
      run: |
        az container create \
          --resource-group anatole-RG \
          --name loki \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/loki:2.9.2 \
          --cpu 1 --memory 2 \
          --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --ports 3100 \
          --environment-variables API_SERVER_HOST=${{ env.API_SERVER_FQDN }}

    # Step 13: Retrieve Loki FQDN (needed for Prometheus and Alertmanager)
    - name: Retrieve Loki FQDN
      id: fqdn_loki
      run: |
        echo "LOKI_FQDN=$(az container show --resource-group anatole-RG --name loki --query 'ipAddress.fqdn' -o tsv)" >> $GITHUB_ENV

    # Step 14: Deploy Prometheus container to Azure Container Instances (ACI)
    - name: Deploy prometheus container to Azure Container Instances (ACI)
      run: |
        az container create \
          --resource-group anatole-RG \
          --name prometheus \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/prometheus:latest \
          --cpu 1 --memory 2 \
          --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --ports 9090 \
          --environment-variables API_SERVER_HOST=${{ env.API_SERVER_FQDN }} LOKI_HOST=${{ env.LOKI_FQDN }}

    # Step 15: Deploy Alertmanager container to Azure Container Instances (ACI)
    - name: Deploy alertmanager container to Azure Container Instances (ACI)
      run: |
        az container create \
          --resource-group anatole-RG \
          --name alertmanager \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/alertmanager:v0.27.0 \
          --cpu 1 --memory 2 \
          --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --ports 9093 \
          --environment-variables API_SERVER_HOST=${{ env.API_SERVER_FQDN }} LOKI_HOST=${{ env.LOKI_FQDN }}

    # Step 16: Deploy Grafana container to Azure Container Instances (ACI)
    - name: Deploy grafana container to Azure Container Instances (ACI)
      run: |
        az container create \
          --resource-group anatole-RG \
          --name grafana \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/grafana:latest \
          --cpu 1 --memory 2 \
          --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --ports 3000 \
          --environment-variables GF_PATHS_PROVISIONING=/etc/grafana/provisioning GF_AUTH_ANONYMOUS_ENABLED=true GF_AUTH_ANONYMOUS_ORG_ROLE=Admin GF_UNIFIED_ALERTING_ENABLED=true GF_ALERTING_ENABLED=false LOKI_HOST=${{ env.LOKI_FQDN }} PROMETHEUS_HOST=${{ env.PROMETHEUS_FQDN }} ALERTMANAGER_HOST=${{ env.ALERTMANAGER_FQDN }}

    # Step 17: Retrieve Grafana FQDN (optional)
    - name: Retrieve Grafana FQDN
      id: fqdn_grafana
      run: |
        echo "GRAFANA_FQDN=$(az container show --resource-group anatole-RG --name grafana --query 'ipAddress.fqdn' -o tsv)" >> $GITHUB_ENV